import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Foot, Footer, Header, NavBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};
//PropsWithChildren
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <NavBar />
        {children}
        <Footer />
        <Foot />
      </body>
    </html>
  );
}
